api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

graphql:
    resource: "@GraphQLBundle/Controller/"

overblog_graphiql_endpoint:
    resource: "@OverblogGraphiQLBundle/Resources/config/routing.xml"
